-- Day 8 of SQL Challenge with my SQL workbench 
-- Get the total Revenue Generated by each Manager and Location

SELECT a.`Location ID`, e.Manager, a.Quantity*p.ProductPrice AS Revenue
FROM all_sales AS a
RIGHT JOIN dimproduct AS p
ON a.ProductID = p.ProductID
JOIN dimemployee AS e
ON e.ID = a.SalesRepID
GROUP BY e.Manager, a.`Location ID`
