-- Day 12 of SQL with MySQL workbench Challenge 
-- Get the total revenue generated by each Chanel and Subchannel for the Month of January 2022 only.


SELECT dc.Channel AS Channels, ds.Subchannel, sum(all_sales.Quantity * dp.ProductPrice) AS Jan_Revenue
FROM all_sales
LEFT JOIN dimsubchannel AS ds 
ON all_sales.SubChannelID = ds.SubChannelID
LEFT JOIN dimchannel AS dc 
ON ds.ChannelID = dc.ChannelID
JOIN dimproduct AS dp 
ON all_sales.ProductID = dp.ProductID
WHERE 
Year(STR_TO_DATE(all_sales.MonthYear, '%m/%d/%Y')) = 2022  And Month(STR_TO_DATE(all_sales.MonthYear, '%m/%d/%Y')) = 1 -- STR_TO_DATE function is use to convert the column value to date format.
GROUP BY Subchannel,Channel
ORDER BY Jan_Revenue;
